authsystem/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/',    views.login,    name='login'),
    path('register/', views.register, name='register'),
    path('logout/',   views.logout,   name='logout'),
]

file_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('authsystem.urls', 'authsystem'), namespace='authsystem')),
    path('', include(('filesystem.urls', 'filesystem'), namespace='filesystem')),
    path('', views.index, name='index'),
]

filesystem/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('create/', views.add_file, name='create'),
    path('download/<str:id>', views.download_file, name='download'),
    path('delete/<str:id>', views.delete_file, name='delete'),
    path('create_link/<str:id>', views.make_file_public_available, name='create_link'),
    path('remove_link/<str:id>', views.make_file_public_unavailable, name='remove_link'),
    path('public_access/<str:public_link>', views.public_file_access, name='public_access')
]

templates/base.html
<head>
 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script>
 function copyTextToClipboard(text) {
  var node = document.createElement('textarea');
  var selection = document.getSelection();

  node.textContent = text;
  document.body.appendChild(node);

  selection.removeAllRanges();
  node.select();
  document.execCommand('copy');

  selection.removeAllRanges();
  document.body.removeChild(node);
  window.alert('Link was copied')
}
  </script>
</head>
<body>
    <div class='navbar navbar-fixed-top'>
        <div class='container'>
            <div class='collapse navbar-collapse' >
                <ul class='nav navbar-nav'>
                {% if user.is_authenticated %}
                    <li class='nav'><a href={% url 'index' %} ><b>{{ user.username }}</b></a></li>
                    <li class='nav-item active' ><a class='btn btn-outline-light' href={% url 'authsystem:logout' %}>logout</a></li>
                {% endif %}                    
                </ul>
            </div>
        </div>
    </div>
    <div class='container'>
        <div style='padding: 80px'>
        {% if user.is_authenticated %}
        {% block content %}
        {% endblock %}
        {% else %}
        {% block auth %}
        {% endblock %}
        {% endif %}
        </div> 
    </div>
</body>

templates/index.html
{% extends "base.html" %}
{% block content %}
    <p><a class='btn btn-success' href={% url 'filesystem:create' %}>Upload file</a></p>
        <table class="table table-hover table-striped table-bordered" style='text-align: center'>
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Public link</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
        {% for file in files %}
        <tr>
          <td>{{ file.virtual_name }}</td>
          {% if file.public_link != '' %}
          <td><input class='btn btn-primary' type="button" value="Copy link" onclick="copyTextToClipboard('{{ request.scheme }}://{{ request.get_host }}{% url 'filesystem:public_access' file.public_link %}')"> <a class='btn btn-warning' href={% url 'filesystem:remove_link' file.id %}>Remove link</a></td>
          {% else %}  
          <td><a class='btn btn-primary' href={% url 'filesystem:create_link' file.id %} >Create link</a></td>
          {% endif %}
          <td><a class='btn btn-success' href={% url 'filesystem:download' file.id %} download = "{{ file.virtual_name }}">Download</a></td>
          <td><a class='btn btn-danger' href={% url 'filesystem:delete' file.id %}>Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
{% endblock %}