authsystem/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/',    views.login,    name='login'),
    path('register/', views.register, name='register'),
    path('logout/',   views.logout,   name='logout'),
]

file_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('authsystem.urls', 'authsystem'), namespace='authsystem')),
    path('', include(('filesystem.urls', 'filesystem'), namespace='filesystem')),
    path('', views.index, name='index'),
]

authsystem/models.py
from django.db import models
# Create your models here.

authsystem/views.py
from django.shortcuts import render
import django.contrib.auth as auth
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, reverse
# Create your views here.


def login(request):
    current_user = request.user
    if request.method == 'POST':
        login_form = auth.forms.AuthenticationForm(data=request.POST)
    else:
        login_form = auth.forms.AuthenticationForm()
    context = dict()
    context['login_form'] = login_form
    if request.method == 'POST':
        # logout if user was authenticated
        if current_user.is_authenticated:
            auth.logout(request)
        # if form is not valid, return
        if not login_form.is_valid():
            return render(
                request,
                template_name='login.html',
                context=context
            )
        # trying to authorize
        user = auth.authenticate(
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user is None:
            login_form.add_error(None, "Incorrect login or password")
            return render(request,
                          template_name='login.html',
                          context=context)
        else:
            # attach user to session
            auth.login(request, user)
            return HttpResponseRedirect(reverse('index'))

    if current_user.is_authenticated:
        return HttpResponseRedirect(reverse('index'))
    else:
        return render(request,
                      template_name='login.html',
                      context=context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    # We create form only with POST statement, because
    # form created with {} is recognized as bound one
    if request.method == 'POST':
        register_form = auth.forms.UserCreationForm(data=request.POST)
    else:
        register_form = auth.forms.UserCreationForm()

    context = dict()
    context['register_form'] = register_form
    if request.method == 'POST':
        # if no validation_errors
        if not register_form.is_valid():
            return render(request, template_name='register.html',
                          context=context)
        # Creating new user
        user = auth.models.User.objects.create_user(
            username=request.POST['username'],
            email=None,
            password=request.POST['password1'])
        # Saving new user in database
        user.save()
        # attaching user to session
        auth.login(request, user)
        return HttpResponseRedirect(reverse('index'))

    return render(request, template_name='register.html',
                  context=context)

authsystem/templates/login.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block auth %}
{% if user.is_authenticated %}
    <h2>Change user:</h2>
{% else %}
    <h2>Enter login and password:</h2><td>
{% endif %}
<form method="POST">
  {% csrf_token %}
  {% for field in login_form %}
  <div class='form-group'>
    <label>{{ field.label }}</label>
    <div>{{ field|add_class:"form-control" }}</div>
    <label>{{ field.help_text }}</label>
    <h4 style="color: red">{{ field.errors }}</h4>
  </div>
  {% endfor %}
  {% for error in login_form.non_field_errors %}
    <p><h4 style="color: red">{{ error }}</h4></p>
  {% endfor %}
  <input class='btn btn-success' type="submit" value="Login">
</form>
<h4>If u dont have account, <a class='btn btn-outline-primary' href={% url 'authsystem:register' %}>Register</a></h4>
{% endblock %}-

authsystem/templates/register.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block auth %}
<h6>Back to <a class='btn btn-primary' href={% url 'authsystem:login' %}>Login</a> page</h6>
<form method="POST">
    {% csrf_token %}
    {% for field in register_form %}
        <div class='form-group'>
        <label>{{ field.label }}</label>
        <div>{{ field|add_class:"form-control" }}</div>
        <h6>{{ field.help_text }}</h6>
        <h4 style="color: red">{{ field.errors }}</h4>
    {% endfor %}
    {% for error in register_form.non_field_errors %}
        <p><h4 style="color: red">{{ error }}</h4></p>
    {% endfor %}
    <input class='btn btn-success' type="submit" value="Register">
</form>
{% endblock %}